using System.Collections.Generic;
using SmaugCS.Constants.Enums;

namespace SmaugCS.Constants.Constants
{
    public static class BuilderConstants
    {
        public static readonly List<string> ex_pmisc = new List<string>
                                                  {
                                                      "undefined",
                                                      "vortex",
                                                      "vacuum",
                                                      "slip",
                                                      "ice",
                                                      "mysterious"
                                                  };

        public static List<string> ex_pwater = new List<string>
                                                   {
                                                       "current",
                                                       "wave",
                                                       "whirlpool",
                                                       "geyser"
                                                   };

        public static readonly List<string> ex_pair = new List<string> { "wind", "storm", "coldwind", "breeze" };

        public static readonly List<string> ex_pearth = new List<string> { "landslide", "sinkhole", "quicksand", "earthquake" };

        public static readonly List<string> ex_pfire = new List<string> { "lava", "hotair" };

        public static readonly List<string> ex_flags = new List<string>
                                                  {
                                                      "isdoor",
                                                      "closed",
                                                      "locked",
                                                      "secret",
                                                      "swim",
                                                      "pickproof",
                                                      "fly",
                                                      "climb",
                                                      "dig",
                                                      "eatkey",
                                                      "nopassdoor",
                                                      "hidden",
                                                      "passage",
                                                      "portal",
                                                      "r1",
                                                      "r2",
                                                      "can_climb",
                                                      "can_enter",
                                                      "can_leave",
                                                      "auto",
                                                      "noflee",
                                                      "searchable",
                                                      "bashed",
                                                      "bashproof",
                                                      "nomob",
                                                      "window",
                                                      "can_look",
                                                      "isbolt",
                                                      "bolted"
                                                  };

        public static readonly List<string> sec_flags = new List<string>
                                                   {
                                                       "inside",
                                                       "city",
                                                       "field",
                                                       "forest",
                                                       "hills",
                                                       "mountain",
                                                       "water_swim",
                                                       "water_noswim",
                                                       "underwater",
                                                       "air",
                                                       "desert",
                                                       "dunno",
                                                       "oceanfloor",
                                                       "underground",
                                                       "lava",
                                                       "swamp",
                                                       "r1",
                                                       "r2",
                                                       "r3",
                                                       "r4",
                                                       "r5",
                                                       "r6",
                                                       "r7",
                                                       "r8",
                                                       "r9",
                                                       "r10",
                                                       "r11",
                                                       "r12",
                                                       "r13",
                                                       "r14",
                                                       "r15",
                                                       "r16"
                                                   };


        public static readonly List<string> r_flags = new List<string>
                                                 {
                                                     "dark",
                                                     "death",
                                                     "nomob",
                                                     "indoors",
                                                     "lawful",
                                                     "neutral",
                                                     "chaotic",
                                                     "nomagic",
                                                     "tunnel",
                                                     "private",
                                                     "safe",
                                                     "solitary",
                                                     "petshop",
                                                     "norecall",
                                                     "donation",
                                                     "nodropall",
                                                     "silence",
                                                     "logspeech",
                                                     "nodrop",
                                                     "clanstoreroom",
                                                     "nosummon",
                                                     "noastral",
                                                     "teleport",
                                                     "teleshowdesc",
                                                     "nofloor",
                                                     "nosupplicate",
                                                     "arena",
                                                     "nomissile",
                                                     "r4",
                                                     "r5",
                                                     "prototype",
                                                     "dnd",
                                                     "bfs_mark"
                                                 };

        public static readonly List<string> o_flags = new List<string>
                                                 {
                                                     "glow",
                                                     "hum",
                                                     "dark",
                                                     "loyal",
                                                     "evil",
                                                     "invis",
                                                     "magic",
                                                     "nodrop",
                                                     "bless",
                                                     "antigood",
                                                     "antievil",
                                                     "antineutral",
                                                     "noremove",
                                                     "inventory",
                                                     "antimage",
                                                     "antithief",
                                                     "antiwarrior",
                                                     "anticleric",
                                                     "organic",
                                                     "metal",
                                                     "donation",
                                                     "clanobject",
                                                     "clancorpse",
                                                     "antivampire",
                                                     "antidruid",
                                                     "hidden",
                                                     "poisoned",
                                                     "covering",
                                                     "deathrot",
                                                     "buried",
                                                     "prototype",
                                                     "nolocate",
                                                     "groundrot",
                                                     "lootable",
                                                     "personal",
                                                     "multi_invoke",
                                                     "enchanted"
                                                 };


        public static readonly List<string> w_flags = new List<string>
                                                 {
                                                     "take",
                                                     "finger",
                                                     "neck",
                                                     "body",
                                                     "head",
                                                     "legs",
                                                     "feet",
                                                     "hands",
                                                     "arms",
                                                     "shield",
                                                     "about",
                                                     "waist",
                                                     "wrist",
                                                     "wield",
                                                     "hold",
                                                     "_dual_",
                                                     "ears",
                                                     "eyes",
                                                     "missile",
                                                     "back",
                                                     "face",
                                                     "ankle",
                                                     "r4",
                                                     "r5",
                                                     "r6",
                                                     "r7",
                                                     "r8",
                                                     "r9",
                                                     "r10",
                                                     "r11",
                                                     "r12",
                                                     "r13"
                                                 };

        public static List<string> item_w_flags = new List<string>
                                                      {
                                                          "take",
                                                          "finger",
                                                          "finger",
                                                          "neck",
                                                          "neck",
                                                          "body",
                                                          "head",
                                                          "legs",
                                                          "feet",
                                                          "hands",
                                                          "arms",
                                                          "shield",
                                                          "about",
                                                          "waist",
                                                          "wrist",
                                                          "wrist",
                                                          "wield",
                                                          "hold",
                                                          "dual",
                                                          "ears",
                                                          "eyes",
                                                          "missile",
                                                          "back",
                                                          "face",
                                                          "ankle",
                                                          "ankle",
                                                          "r4",
                                                          "r5",
                                                          "r6",
                                                          "r7",
                                                          "r8",
                                                          "r9",
                                                          "r10",
                                                          "r11",
                                                          "r12",
                                                          "r13"
                                                      };

        public static readonly List<string> area_flags = new List<string>
                                                    {
                                                        "nopkill",
                                                        "freekill",
                                                        "noteleport",
                                                        "spelllimit",
                                                        "prototype",
                                                        "r5",
                                                        "r6",
                                                        "r7",
                                                        "r8",
                                                        "r9",
                                                        "r10",
                                                        "r11",
                                                        "r12",
                                                        "r13",
                                                        "r14",
                                                        "r15",
                                                        "r16",
                                                        "r17",
                                                        "r18",
                                                        "r19",
                                                        "r20",
                                                        "r21",
                                                        "r22",
                                                        "r23",
                                                        "r24",
                                                        "r25",
                                                        "r26",
                                                        "r27",
                                                        "r28",
                                                        "r29",
                                                        "r30",
                                                        "r31"
                                                    };

        public static readonly List<string> o_types = new List<string>
                                                 {
                                                     "none",
                                                     "light",
                                                     "scroll",
                                                     "wand",
                                                     "staff",
                                                     "weapon",
                                                     "_fireweapon",
                                                     "_missile",
                                                     "treasure",
                                                     "armor",
                                                     "potion",
                                                     "_worn",
                                                     "furniture",
                                                     "trash",
                                                     "_oldtrap",
                                                     "container",
                                                     "_note",
                                                     "drinkcon",
                                                     "key",
                                                     "food",
                                                     "money",
                                                     "pen",
                                                     "boat",
                                                     "corpse",
                                                     "corpse_pc",
                                                     "fountain",
                                                     "pill",
                                                     "blood",
                                                     "bloodstain",
                                                     "scraps",
                                                     "pipe",
                                                     "herbcon",
                                                     "herb",
                                                     "incense",
                                                     "fire",
                                                     "book",
                                                     "switch",
                                                     "lever",
                                                     "pullchain",
                                                     "button",
                                                     "dial",
                                                     "rune",
                                                     "runepouch",
                                                     "match",
                                                     "trap",
                                                     "map",
                                                     "portal",
                                                     "paper",
                                                     "tinder",
                                                     "lockpick",
                                                     "spike",
                                                     "disease",
                                                     "oil",
                                                     "fuel",
                                                     "_empty1",
                                                     "_empty2",
                                                     "missileweapon",
                                                     "projectile",
                                                     "quiver",
                                                     "shovel",
                                                     "salve",
                                                     "cook",
                                                     "keyring",
                                                     "odor",
                                                     "chance",
                                                     "mix"
                                                 };

        public static readonly List<string> a_types = new List<string>
                                                 {
                                                     "none",
                                                     "strength",
                                                     "dexterity",
                                                     "intelligence",
                                                     "wisdom",
                                                     "constitution",
                                                     "sex",
                                                     "class",
                                                     "level",
                                                     "age",
                                                     "height",
                                                     "weight",
                                                     "mana",
                                                     "hit",
                                                     "move",
                                                     "gold",
                                                     "experience",
                                                     "armor",
                                                     "hitroll",
                                                     "damroll",
                                                     "save_poison",
                                                     "save_rod",
                                                     "save_para",
                                                     "save_breath",
                                                     "save_spell",
                                                     "charisma",
                                                     "affected",
                                                     "resistant",
                                                     "immune",
                                                     "susceptible",
                                                     "weaponspell",
                                                     "luck",
                                                     "backstab",
                                                     "pick",
                                                     "track",
                                                     "steal",
                                                     "sneak",
                                                     "hide",
                                                     "palm",
                                                     "detrap",
                                                     "dodge",
                                                     "peek",
                                                     "scan",
                                                     "gouge",
                                                     "search",
                                                     "mount",
                                                     "disarm",
                                                     "kick",
                                                     "parry",
                                                     "bash",
                                                     "stun",
                                                     "punch",
                                                     "climb",
                                                     "grip",
                                                     "scribe",
                                                     "brew",
                                                     "wearspell",
                                                     "removespell",
                                                     "emotion",
                                                     "mentalstate",
                                                     "stripsn",
                                                     "remove",
                                                     "dig",
                                                     "full",
                                                     "thirst",
                                                     "drunk",
                                                     "blood",
                                                     "cook",
                                                     "recurringspell",
                                                     "contagious",
                                                     "xaffected",
                                                     "odor",
                                                     "roomflag",
                                                     "sectortype",
                                                     "roomlight",
                                                     "televnum",
                                                     "teledelay"
                                                 };

        public static readonly List<string> a_flags = new List<string>
                                                 {
                                                     "blind",
                                                     "invisible",
                                                     "detect_evil",
                                                     "detect_invis",
                                                     "detect_magic",
                                                     "detect_hidden",
                                                     "hold",
                                                     "sanctuary",
                                                     "faerie_fire",
                                                     "infrared",
                                                     "curse",
                                                     "_flaming",
                                                     "poison",
                                                     "protect",
                                                     "_paralysis",
                                                     "sneak",
                                                     "hide",
                                                     "sleep",
                                                     "charm",
                                                     "flying",
                                                     "pass_door",
                                                     "floating",
                                                     "truesight",
                                                     "detect_traps",
                                                     "scrying",
                                                     "fireshield",
                                                     "shockshield",
                                                     "r1",
                                                     "iceshield",
                                                     "possess",
                                                     "berserk",
                                                     "aqua_breath",
                                                     "recurringspell",
                                                     "contagious",
                                                     "acidmist",
                                                     "venomshield"
                                                 };

        public static readonly List<string> act_flags = new List<string>
                                                   {
                                                       "npc",
                                                       "sentinel",
                                                       "scavenger",
                                                       "r1",
                                                       "r2",
                                                       "aggressive",
                                                       "stayarea",
                                                       "wimpy",
                                                       "pet",
                                                       "train",
                                                       "practice",
                                                       "immortal",
                                                       "deadly",
                                                       "polyself",
                                                       "meta_aggr",
                                                       "guardian",
                                                       "running",
                                                       "nowander",
                                                       "mountable",
                                                       "mounted",
                                                       "scholar",
                                                       "secretive",
                                                       "hardhat",
                                                       "mobinvis",
                                                       "noassist",
                                                       "autonomous",
                                                       "pacifist",
                                                       "noattack",
                                                       "annoying",
                                                       "statshield",
                                                       "prototype"
                                                   };

        public static readonly List<string> pc_flags = new List<string>
                                                  {
                                                      "r1",
                                                      "deadly",
                                                      "unauthed",
                                                      "norecall",
                                                      "nointro",
                                                      "gag",
                                                      "retired",
                                                      "guest",
/* changed "r8" to "" so players on watch can't see it  -- Gorog */
                                                      "nosummon",
                                                      "pager",
                                                      "notitled",
                                                      "groupwho",
                                                      "diagnose",
                                                      "highgag",
                                                      "",
                                                      "nstart",
                                                      "dnd",
                                                      "idle",
                                                      "hints",
                                                      "r19",
                                                      "r20",
                                                      "r21",
                                                      "r22",
                                                      "r23",
                                                      "r24",
                                                      "r25",
                                                      "r26",
                                                      "r27",
                                                      "r28",
                                                      "r29",
                                                      "r30",
                                                      "r31"
                                                  };

        public static readonly List<string> plr_flags = new List<string>
                                                   {
                                                       "npc",
                                                       "boughtpet",
                                                       "shovedrag",
                                                       "autoexits",
                                                       "autoloot",
                                                       "autosac",
                                                       "blank",
                                                       "outcast",
                                                       "brief",
                                                       "combine",
                                                       "prompt",
                                                       "telnet_ga",
                                                       "holylight",
                                                       "wizinvis",
                                                       "roomvnum",
                                                       "silence",
                                                       "noemote",
                                                       "attacker",
                                                       "notell",
                                                       "log",
                                                       "deny",
                                                       "freeze",
                                                       "thief",
                                                       "killer",
                                                       "litterbug",
                                                       "ansi",
                                                       "rip",
                                                       "nice",
                                                       "flee",
                                                       "autogold",
                                                       "automap",
                                                       "afk",
                                                       "invisprompt",
                                                       "compass"
                                                   };

        public static readonly List<string> trap_flags = new List<string>
                                                    {
                                                        "room",
                                                        "obj",
                                                        "enter",
                                                        "leave",
                                                        "open",
                                                        "close",
                                                        "get",
                                                        "put",
                                                        "pick",
                                                        "unlock",
                                                        "north",
                                                        "south",
                                                        "east",
                                                        "west",
                                                        "up",
                                                        "down",
                                                        "examine",
                                                        "northeast",
                                                        "northwest",
                                                        "southeast",
                                                        "southwest",
                                                        "r6",
                                                        "r7",
                                                        "r8",
                                                        "r9",
                                                        "r10",
                                                        "r11",
                                                        "r12",
                                                        "r13",
                                                        "r14",
                                                        "r15"
                                                    };

        public static readonly List<string> cmd_flags = new List<string>
                                                   {
                                                       "possessed",
                                                       "polymorphed",
                                                       "r1",
                                                       "r2",
                                                       "r3",
                                                       "r4",
                                                       "r5",
                                                       "r6",
                                                       "r7",
                                                       "r8",
                                                       "r9",
                                                       "r10",
                                                       "r11",
                                                       "r12",
                                                       "r13",
                                                       "r14",
                                                       "r15",
                                                       "r16",
                                                       "r17",
                                                       "r18",
                                                       "r19",
                                                       "r20",
                                                       "r21",
                                                       "r22",
                                                       "r23",
                                                       "r24",
                                                       "r25",
                                                       "r26",
                                                       "r27",
                                                       "r28",
                                                       "r29",
                                                       "r30"
                                                   };

        public static readonly List<string> wear_locs = new List<string>
                                                   {
                                                       "light",
                                                       "finger1",
                                                       "finger2",
                                                       "neck1",
                                                       "neck2",
                                                       "body",
                                                       "head",
                                                       "legs",
                                                       "feet",
                                                       "hands",
                                                       "arms",
                                                       "shield",
                                                       "about",
                                                       "waist",
                                                       "wrist1",
                                                       "wrist2",
                                                       "wield",
                                                       "hold",
                                                       "dual_wield",
                                                       "ears",
                                                       "eyes",
                                                       "missile_wield",
                                                       "back",
                                                       "face",
                                                       "ankle1",
                                                       "ankle2"
                                                   };

        public static readonly List<string> ris_flags = new List<string>
                                                   {
                                                       "fire",
                                                       "cold",
                                                       "electricity",
                                                       "energy",
                                                       "blunt",
                                                       "pierce",
                                                       "slash",
                                                       "acid",
                                                       "poison",
                                                       "drain",
                                                       "sleep",
                                                       "charm",
                                                       "hold",
                                                       "nonmagic",
                                                       "plus1",
                                                       "plus2",
                                                       "plus3",
                                                       "plus4",
                                                       "plus5",
                                                       "plus6",
                                                       "magic",
                                                       "paralysis",
                                                       "r1",
                                                       "r2",
                                                       "r3",
                                                       "r4",
                                                       "r5",
                                                       "r6",
                                                       "r7",
                                                       "r8",
                                                       "r9",
                                                       "r10"
                                                   };

        public static readonly List<string> trig_flags = new List<string>
                                                    {
                                                        "up",
                                                        "unlock",
                                                        "lock",
                                                        "d_north",
                                                        "d_south",
                                                        "d_east",
                                                        "d_west",
                                                        "d_up",
                                                        "d_down",
                                                        "door",
                                                        "container",
                                                        "open",
                                                        "close",
                                                        "passage",
                                                        "oload",
                                                        "mload",
                                                        "teleport",
                                                        "teleportall",
                                                        "teleportplus",
                                                        "death",
                                                        "cast",
                                                        "fakeblade",
                                                        "rand4",
                                                        "rand6",
                                                        "trapdoor",
                                                        "anotherroom",
                                                        "usedial",
                                                        "absolutevnum",
                                                        "showroomdesc",
                                                        "autoreturn",
                                                        "r2",
                                                        "r3"
                                                    };

        public static readonly List<string> part_flags = new List<string>
                                                    {
                                                        "head",
                                                        "arms",
                                                        "legs",
                                                        "heart",
                                                        "brains",
                                                        "guts",
                                                        "hands",
                                                        "feet",
                                                        "fingers",
                                                        "ear",
                                                        "eye",
                                                        "long_tongue",
                                                        "eyestalks",
                                                        "tentacles",
                                                        "fins",
                                                        "wings",
                                                        "tail",
                                                        "scales",
                                                        "claws",
                                                        "fangs",
                                                        "horns",
                                                        "tusks",
                                                        "tailattack",
                                                        "sharpscales",
                                                        "beak",
                                                        "haunches",
                                                        "hooves",
                                                        "paws",
                                                        "forelegs",
                                                        "feathers",
                                                        "r1",
                                                        "r2"
                                                    };

        public static readonly List<string> attack_flags = new List<string>
                                                      {
                                                          "bite",
                                                          "claws",
                                                          "tail",
                                                          "sting",
                                                          "punch",
                                                          "kick",
                                                          "trip",
                                                          "bash",
                                                          "stun",
                                                          "gouge",
                                                          "backstab",
                                                          "feed",
                                                          "drain",
                                                          "firebreath",
                                                          "frostbreath",
                                                          "acidbreath",
                                                          "lightnbreath",
                                                          "gasbreath",
                                                          "poison",
                                                          "nastypoison",
                                                          "gaze",
                                                          "blindness",
                                                          "causeserious",
                                                          "earthquake",
                                                          "causecritical",
                                                          "curse",
                                                          "flamestrike",
                                                          "harm",
                                                          "fireball",
                                                          "colorspray",
                                                          "weaken",
                                                          "spiralblast"
                                                      };

        public static readonly List<string> defense_flags = new List<string>
                                                       {
                                                           "parry",
                                                           "dodge",
                                                           "heal",
                                                           "curelight",
                                                           "cureserious",
                                                           "curecritical",
                                                           "dispelmagic",
                                                           "dispelevil",
                                                           "sanctuary",
                                                           "fireshield",
                                                           "shockshield",
                                                           "shield",
                                                           "bless",
                                                           "stoneskin",
                                                           "teleport",
                                                           "monsum1",
                                                           "monsum2",
                                                           "monsum3",
                                                           "monsum4",
                                                           "disarm",
                                                           "iceshield",
                                                           "grip",
                                                           "truesight",
                                                           "acidmist",
                                                           "venomshield"
                                                       };

        public static readonly List<string> npc_position = new List<string>
                                                      {
                                                          "dead",
                                                          "mortal",
                                                          "incapacitated",
                                                          "stunned",
                                                          "sleeping",
                                                          "resting",
                                                          "sitting",
                                                          "berserk",
                                                          "aggressive",
                                                          "fighting",
                                                          "defensive",
                                                          "evasive",
                                                          "standing",
                                                          "mounted",
                                                          "shove",
                                                          "drag"
                                                      };

        public static readonly List<string> npc_sex = new List<string>
                                                 {
                                                     "neuter",
                                                     "male",
                                                     "female"
                                                 };

        public static readonly List<string> mprog_flags = new List<string>
                                                     {
                                                         "act",
                                                         "speech",
                                                         "rand",
                                                         "fight",
                                                         "death",
                                                         "hitprcnt",
                                                         "entry",
                                                         "greet",
                                                         "allgreet",
                                                         "give",
                                                         "bribe",
                                                         "hour",
                                                         "time",
                                                         "wear",
                                                         "remove",
                                                         "sac",
                                                         "look",
                                                         "exa",
                                                         "zap",
                                                         "get",
                                                         "drop",
                                                         "damage",
                                                         "repair",
                                                         "randiw",
                                                         "speechiw",
                                                         "pull",
                                                         "push",
                                                         "sleep",
                                                         "rest",
                                                         "leave",
                                                         "script",
                                                         "use",
                                                         "sell",
                                                         "tell",
                                                         "command"
                                                     };

        public static readonly Dictionary<MudProgTypes, string> mprog_types = new Dictionary<MudProgTypes, string>
            {
                {MudProgTypes.InFile, "in_file_prog"},
                {MudProgTypes.Act, "act_prog"},
                {MudProgTypes.Speech, "speech_prog"},
                {MudProgTypes.Random, "rand_prog"},
                {MudProgTypes.Fight, "fight_prog"},
                {MudProgTypes.HitPercent, "hitprcnt_prog"},
                {MudProgTypes.Death, "death_prog"},
                {MudProgTypes.Entry, "entry_prog"},
                {MudProgTypes.Greet, "greet_prog"},
                {MudProgTypes.GreetAll, "all_greet_prog"},
                {MudProgTypes.Give, "give_prog"},
                {MudProgTypes.Bribe, "bribe_prog"},
                {MudProgTypes.Hour, "hour_prog"},
                {MudProgTypes.Time, "time_prog"},
                {MudProgTypes.Wear, "wear_prog"},
                {MudProgTypes.Remove, "remove_prog"},
                {MudProgTypes.Sacrifice, "sac_prog"},
                {MudProgTypes.Look, "look_prog"},
                {MudProgTypes.Examine, "exa_prog"},
                {MudProgTypes.Zap, "zap_prog"},
                {MudProgTypes.Get, "get_prog"},
                {MudProgTypes.Drop, "drop_prog"},
                {MudProgTypes.Repair, "repair_prog"},
                {MudProgTypes.Damage, "damage_prog"},
                {MudProgTypes.Pull, "pull_prog"},
                {MudProgTypes.Push, "push_prog"},
                {MudProgTypes.Script, "script_prog"},
                {MudProgTypes.Sleep, "sleep_prog"},
                {MudProgTypes.Rest, "rest_prog"},
                {MudProgTypes.Leave, "leave_prog"},
                {MudProgTypes.Use, "use_prog"}
            };

        public static string mprog_type_to_name(MudProgTypes type)
        {
            return mprog_types.ContainsKey(type) ? mprog_types[type] : "ERROR_PROG";
        }
    }
}
