CREATE TABLE [live].[User]
(
	[UserID] BIGINT IDENTITY(1, 1) NOT NULL, 
	[Username] NVARCHAR(25) NOT NULL,
	[Password] NVARCHAR(256) NOT NULL,
	[PreHashID] SMALLINT NOT NULL,
	[PostHashID] SMALLINT NOT NULL,
    [CreatedOn] DATETIME NULL,
	[DeletedOn] DATETIME NULL,
	[LastLogin] DATETIME NOT NULL
	CONSTRAINT pk_User
		PRIMARY KEY CLUSTERED ([UserID])  
);
GO

ALTER TABLE live.[User]
	ADD CONSTRAINT FK_User_PreHashID
		FOREIGN KEY (PreHashID) 
		REFERENCES live.[Hash] (HashID)
		ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

CREATE NONCLUSTERED INDEX [IDX_User_PreHashID]
    ON [live].[User]([PreHashID] ASC);
GO

ALTER TABLE live.[User]
	ADD CONSTRAINT FK_User_PostHashID
		FOREIGN KEY (PostHashID) 
		REFERENCES live.[Hash] (HashID)
		ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

CREATE NONCLUSTERED INDEX [IDX_User_PostHashID]
    ON [live].[User]([PostHashID] ASC);
GO