CREATE TABLE [live].[GameState]
(
	[GameStateID] INT IDENTITY NOT NULL, 
    [GameYear] SMALLINT NOT NULL,
	[GameMonth] SMALLINT NOT NULL,
	[GameDay] SMALLINT NOT NULL,
	[GameHour] SMALLINT NOT NULL,

	CONSTRAINT pk_GameState
		PRIMARY KEY CLUSTERED ([GameStateID] ASC)  
);
GO
