--PRINT 'Starting ref.WearLocation Syncronization';
--GO

--DECLARE @Source TABLE (
--    WearLocationID TINYINT NOT NULL
--    , Name VARCHAR(50) NOT NULL
--	, Value INT NOT NULL
--	, ShortName VARCHAR(100) NOT NULL
--	, LongName VARCHAR(1024) NOT NULL);

--SET NOCOUNT ON;
--INSERT @Source (WearLocationID, Name, Value, ShortName, LongName)
--VALUES (1, N'wear_head', 1, 'Head', 'Worn on Head'),
--	   (2, N'wear_face', 2, 'Face', 'Worn on Face'),
--	   (3, N'wear_ear_left', 4, 'Left Ear', 'Worn in Left Ear'),
--	   (4, N'wear_ear_right', 8, 'Right Ear', 'Worn in Right Ear'),
--	   (5, N'wear_brow', 16, 'Brow', 'Worn on Brow'),
--	   (6, N'wear_neck', 32, 'Neck', 'Worn about Neck'),
--	   (7, N'wear_wrist_left', 64, 'Left Wrist', 'Worn on Left Wrist'),
--	   (8, N'wear_wrist_right', 128, 'Right Wrist', 'Worn on Rigth Wrist'),
--	   (9, N'wear_wrist_both', 256, 'Both Wrists', 'Worn on Both Wrists'),
--	   (10, N'wear_hand_left', 512, 'Left Hand', 'Held in Left Hand'),
--	   (11, N'wear_hand_right', 1024, 'Right Hand', 'Held in Right Hand'),
--	   (12, N'wear_hand_both', 2048, 'Both Hands', 'Held in Both Hands'),
--	   (13, N'wear_finger_left', 4096, 'Left Ring Finger', 'Worn on Left Ring Finger'),
--	   (14, N'wear_finger_right', 8192, 'Right Ring Finger', 'Worn on Right Ring Finger'),
--	   (15, N'wear_chest', 16384, 'Chest', 'Worn on Torso'),
--	   (16, N'wear_back', 32768, 'Back', 'Worn on Back'),
--	   (17, N'wear_waist', 65536, 'Waist', 'Worn about Waist'),
--	   (18, N'wear_legs', 131072, 'Legs', 'Worn on Legs'),
--	   (19, N'wear_arms', 262144, 'Arms', 'Worn on Arms'),
--	   (20, N'wear_ankle_left', 524288, 'Left Ankle', 'Worn on Left Ankle'),
--	   (21, N'wear_ankle_right', 1048576, 'Right Ankle', 'Worn on Right Ankle'),
--	   (22, N'wear_ankle_both', 2097152, 'Both Ankles', 'Worn on Both Ankles'),
--	   (23, N'wear_feet', 4194304, 'Feet', 'Worn on Feet'),
--	   (24, N'wear_body', 8388608, 'Body', 'Worn about Body'),
--	   (25, N'none', 0, 'None', 'None');
--SET NOCOUNT OFF;

--MERGE ref.WearLocation AS t
--USING @Source AS s
--    ON s.WearLocationID = t.WearLocationID
--WHEN NOT MATCHED BY TARGET THEN
--    INSERT (WearLocationID, Name, Value, ShortName, LongName)
--    VALUES (s.WearLocationID, s.Name, s.Value, s.ShortName, s.LongName)
--WHEN MATCHED AND (t.Name <> s.Name)
--    THEN UPDATE SET t.Name = s.Name
--		, t.Value = s.Value
--		, t.ShortName = s.ShortName
--		, t.LongName = s.LongName
--WHEN NOT MATCHED BY SOURCE THEN
--    DELETE;

--PRINT 'Done Synchronizing ref.WearLocation';
--GO
