# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        # If you're using a preview SDK, uncomment the next line:
        # include-prerelease: true

    - name: Show dotnet info
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore ./Source/SmaugCS.sln

    - name: Build
      run: dotnet build ./Source/SmaugCS.sln --no-restore

    - name: Test
      run: dotnet test ./Source/SmaugCS.sln --logger trx --results-directory "TestResults" --no-build --verbosity normal

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results
        path: TestResults
      if: ${{ always() }}